export default mockUserDetails = {
  '1': {
    fullName: 'Josh Holloway',
    tagName: '@josh_h',
    buddies: 0,
    appAge: 'New User',
    interests: ['Hiking', 'Photography', 'Reading'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=1',
  },
  '2': {
    fullName: 'Emily Clark',
    tagName: '@emclark',
    buddies: 0,
    appAge: 'New User',
    interests: ['Music', 'Yoga', 'Blogging'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=2',
  },
  '3': {
    fullName: 'Leo Gardner',
    tagName: '@leog',
    buddies: 0,
    appAge: 'New User',
    interests: ['Gaming', 'Travel', 'Cooking'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=3',
  },
  '4': {
    fullName: 'Sophia Turner',
    tagName: '@sophie_t',
    buddies: 0,
    appAge: 'New User',
    interests: ['Fashion', 'Art', 'Reading', 'Music', 'Yoga', 'Blogging'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=4',
  },
  '5': {
    fullName: 'Michael Santos',
    tagName: '@mikes',
    buddies: 0,
    appAge: 'New User',
    interests: ['Fitness', 'Technology', 'Photography'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=5',
  },
  '6': {
    fullName: 'Isabella Pearson',
    tagName: '@izzy_p',
    buddies: 0,
    appAge: 'New User',
    interests: ['Dance', 'Cooking', 'Travel'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=6',
  },
  '7': {
    fullName: 'Ethan Hunt',
    tagName: '@ethan_h',
    buddies: 0,
    appAge: 'New User',
    interests: ['Skydiving', 'Scuba Diving', 'Rock Climbing'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=7',
  },
  '8': {
    fullName: 'Daniel Mocanu',
    tagName: '@danmocanu',
    buddies: 15,
    appAge: '1 year',
    interests: ['Music', 'Travel', 'Photography'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=8',
  },
  '9': {
    fullName: 'Michael Jackson',
    tagName: '@mikejack',
    buddies: 50,
    appAge: '2 years',
    interests: ['Dance', 'Singing', 'Charity'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=9',
  },
  '10': {
    fullName: 'Ur Catgirl',
    tagName: '@uwu',
    buddies: 50,
    appAge: '2 years',
    interests: ['Dance', 'Singing', 'Anime'],
    backgroundImageUri: 'https://picsum.photos/seed/picsum/600/300',
    avatarUri: 'https://picsum.photos/200?random=10',
  },
};
